{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "todo-deployment",
    "labels": {
      "app": "todo"
    }
  },
  "spec": {
    "replicas": 3,
    "selector": {
      "matchLabels": {
        "app": "todo"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "todo"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "todo",
            "image": "pmcakstraining.azurecr.io/simon_daniel/todo:0.0.15",
            "ports": [
              {
                "containerPort": 3000
              }
            ],
            "volumeMounts": [
              {
                "mountPath": "/data",
                "name": "todo-db"
              }
            ]
          }
        ],
        "volumes": [
          {
            "name": "todo-db",
            "persistentVolumeClaim": {
              "claimName": "todo-db"
            }
          }
        ]
      }
    }
  }
}
