{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "todo-deployment",
    "labels": {
      "app": "todo"
    }
  },
  "spec": {
    "selector": {
      "matchLabels": {
        "app": "todo"
      }
    },
    "replicas": 1,
    "template": {
      "metadata": {
        "labels": {
          "app": "todo"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "todo",
            "image": "pmcakstraining.azurecr.io/simon_daniel/todo:0.0.15",
            "ports": [
              {
                "containerPort": 3000
              }
            ],
            "volumeMounts": [
              {
                "mountPath": "/data",
                "name": "todo-db"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "500m",
                "memory": "256Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "128Mi"
              }
            }
          }
        ],
        "tolerations": [
          {
            "key": "purpose",
            "operator": "Equal",
            "value": "todo",
            "effect": "NoSchedule"
          }
        ],
        "nodeSelector": {
          "app": "todo"
        },
        "affinity": {
          "podAntiAffinity": {
            "requiredDuringSchedulingIgnoredDuringExecution": [
              {
                "labelSelector": {
                  "matchExpressions": [
                    {
                      "key": "app",
                      "operator": "In",
                      "values": [
                        "todo-backend"
                      ]
                    }
                  ]
                },
                "topologyKey": "topology.kubernetes.io/hostname"
              }
            ]
          }
        },
        "volumes": [
          {
            "name": "todo-db",
            "persistentVolumeClaim": {
              "claimName": "todo-db"
            }
          }
        ]
      }
    }
  }
}