{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "todo-fe-deployment",
    "labels": {
      "app": "todo-fe"
    }
  },
  "spec": {
    "replicas": 2,
    "selector": {
      "matchLabels": {
        "app": "todo-fe"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "todo-fe"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "todo-fe",
            "image": "pmcakstraining.azurecr.io/simon_daniel/todo-fe:0.0.10",
            "ports": [
              {
                "containerPort": 3000
              }
            ]
          }
        ]
      }
    }
  }
}